FROM node:22-alpine

WORKDIR /app

COPY argus-frontend/package*.json ./

RUN npm install

COPY argus-frontend/src ./src
COPY argus-frontend/public ./public
COPY argus-frontend/tsconfig.json ./

EXPOSE 3000

ENV CI=false
ENV BROWSER=none

CMD ["npm", "start"]
