"""add_zones_and_cross_camera_links

Revision ID: eda51162e7c0
Revises: 8386e4420884
Create Date: 2026-06-15 03:43:46.236567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda51162e7c0'
down_revision: Union[str, Sequence[str], None] = '8386e4420884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_on_enter', sa.Boolean(), nullable=False),
    sa.Column('alert_on_dwell', sa.Boolean(), nullable=False),
    sa.Column('dwell_threshold_seconds', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_camera_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('identity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_track_id', sa.Integer(), nullable=True),
    sa.Column('source_camera_id', sa.Integer(), nullable=False),
    sa.Column('dest_track_id', sa.Integer(), nullable=True),
    sa.Column('dest_camera_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dest_camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['dest_track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['source_camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['source_track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cross_camera_links')
    op.drop_table('zones')
    # ### end Alembic commands ###
